#!/usr/bin/env sh

# // Load Scripting addon //
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

# // Config //
yabai -m config mouse_follows_focus off
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config window_animation_duration    0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_placement             second_child
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_shadow                float

yabai -m config layout bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   4

# // Rules //
# Floating window
yabai -m rule --add title="JetBrains Toolbox" manage=off mouse_follows_focus=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Stats" manage=off mouse_follows_focus=off
yabai -m rule --add app="iStat Menus" manage=off mouse_follows_focus=off
yabai -m rule --add app="Things" grid=10:3:1:1:1:8 mouse_follows_focus=on sticky=on
yabai -m rule --add app="choose" manage=off mouse_follows_focus=off
yabai -m rule --add app="CleanShot X" manage=off mouse_follows_focus=off
yabai -m rule --add app="Last.fm Scrobbler" manage=off mouse_follows_focus=off
