include colors_light.conf
font_family MesloLGS Nerd Font
font_size 13
window_padding_width 12
confirm_os_window_close 0
text_antialiasing true
macos_titlebar_color background
disable_ligatures never
scrollback_indicator_opacity 0
